technical_design_task:
  description: >
    Create comprehensive technical design for {domain} system including:
    - Architecture diagrams
    - Technology stack justification
    - Scalability considerations
    - Security requirements
  expected_output: >
    Technical specification document containing:
    1. C4 model diagrams (Level 1-3)
    2. Tech stack comparison matrix
    3. Failure mode analysis
    4. Data flow diagrams
  agent: technical_lead

feature_development_task:
  description: >
    Implement {feature} using {tech_stack} following:
    - Clean code principles
    - Test-driven development
    - CI/CD pipeline requirements
    - Documentation standards
  expected_output: >
    Production-ready implementation containing:
    1. Source code with unit tests
    2. API documentation (OpenAPI Spec)
    3. Deployment configuration
    4. Integration test suite
  agent: full_stack_engineer

quality_assurance_task:
  description: >
    Develop complete quality strategy for {system} including:
    - Automated test plans
    - Security scanning
    - Performance benchmarks
    - Compliance checks ({industry} standards)
  expected_output: >
    Quality assurance package with:
    1. Test automation framework
    2. OWASP Top 10 mitigation plan
    3. Load testing scenarios
    4. Audit checklist
  agent: qa_automation_engineer

deployment_pipeline_task:
  description: >
    Implement cloud-agnostic deployment pipeline for {system} with:
    - Infrastructure as Code
    - GitOps workflows
    - Monitoring integration
    - Rollback capabilities
  expected_output: >
    Deployment package containing:
    1. Terraform/Pulumi modules
    2. ArgoCD configurations
    3. Alerting rules
    4. Disaster recovery playbook
  agent: devops_engineer

ux_implementation_task:
  description: >
    Create user-centric implementation for {domain} system including:
    - Accessibility compliance (WCAG 2.1)
    - Performance optimization
    - Design system integration
    - User feedback mechanisms
  expected_output: >
    UX implementation package with:
    1. Component library
    2. Lighthouse audit report
    3. User journey maps
    4. A/B testing plan
  agent: ux_technical_specialist
